### PR TITLE
phew

### PR DESCRIPTION
**Pull request by Micodlr**
added routes.py

### CODE REVIEW

**Comment by AlexBetita** [comment]
Hey can we use a route folder instead of a routes.py?

**Comment by ouStanleyy** [comment]
beep beep boop

**Comment by ouStanleyy** [comment]
don't do it

**Comment by Micodlr** [comment]
> Hey can we use a route folder instead of a routes.py?

no

**Comment by ouStanleyy** [comment]
> > Hey can we use a route folder instead of a routes.py?
> 
> no

yes

**Pull request merged**
